export const BIST30 = [
  "AKBNK", "ALARK", "ARCLK", "ASELS", "ASTOR", "BIMAS", "BRSAN", "CCOLA", "CWENE", "DOAS",
  "EKGYO", "ENKAI", "EREGL", "FROTO", "GARAN", "GUBRF", "HEKTS", "ISCTR", "KCHOL", "KONTR",
  "KRDMD", "MIATK", "ODAS", "OYAKC", "PETKM", "PGSUS", "SAHOL", "SASA",
  "SISE", "TCELL", "THYAO", "TOASO", "TRALT", "TRMET", "TUPRS", "YKBNK"
];

export const BIST100 = [
  "AEFES", "AGHOL", "AHGAZ", "AKBNK", "AKCNS", "AKFGY", "AKFYE", "AKSA", "AKSEN", "ALARK",
  "ALBRK", "ALFAS", "ARCLK", "ASELS", "ASTOR", "AYDEM", "BIMAS", "BOBET", "BRSAN", "BRYAT",
  "BUCIM", "CANTE", "CCOLA", "CIMSA", "CWENE", "DOAS", "DOHOL", "ECILC", "EGEEN", "EKGYO",
  "ENERY", "ENJSA", "ENKAI", "EREGL", "EUREN", "EUPWR", "FROTO", "GARAN", "GESAN", "GLYHO",
  "GUBRF", "GWIND", "HALKB", "HEKTS", "IPEKE", "ISCTR", "ISDMR", "ISGYO", "ISMEN", "IZENR",
  "KARSN", "KAYSE", "KCAER", "KCHOL", "KLSER", "KMPUR", "KONTR", "KONYA",
  "KRDMD", "MAVI", "MIATK", "MGROS", "ODAS", "OTKAR", "OYAKC", "PENTA", "PETKM", "PGSUS",
  "PNLSN", "QUAGR", "SAHOL", "SASA", "SDTTR", "SISE", "SKBNK", "SMRTG", "SOKM", "TABGD",
  "TAVHL", "TCELL", "THYAO", "TKFEN", "TOASO", "TSKB", "TTKOM", "TTRAK", "TUKAS", "TUPRS",
  "TURSG", "ULKER", "VAKBN", "VESBE", "VESTL", "YEOTK", "YKBNK", "YYLGD", "ZOREN"
];
